services:
  jenkins:
    image: jenkins/jenkins:lts
    ports:
      - 8282:8080
    volumes:
      - jenkins_home:/var/jenkins_home
    restart: unless-stopped
    networks:
      - monitoring

  prometheus:
    image: prom/prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - 9292:9090
    networks:
      - monitoring

  loki:
    image: grafana/loki:2.9.2
    ports:
      - 3200:3100
    command: -config.file=/etc/loki/local-config.yaml
    volumes:
      - ./loki-config.yaml:/etc/loki/local-config.yaml
      - ./loki/index:/loki/index
      - ./loki/chunks:/loki/chunks
      - ./loki/boltdb-cache:/loki/boltdb-cache
    networks:
      - monitoring


  grafana:
    image: grafana/grafana
    ports:
      - 3000:3000
    volumes:
      - grafana-storage:/var/lib/grafana
    networks:
      - monitoring

volumes:
  jenkins_home:
  grafana-storage:

networks:
  monitoring:
